### ISSUE TITLE
当设置每一个Item的frame为屏幕高和屏幕宽的时候 创建15个就内存很高了

### ISSUE THREAD

**Issue by wxh794708907** [alibaba/LazyScrollView#10]
如标题，当设置每一个Item的frame为屏幕高和屏幕宽的时候 创建15个就内存很高了，当设置为150个就直接内存警告了

**Comment by HarrisonXi** [comment]
所提到的150个item是同屏显示的？或者是不可重用的吗？

**Comment by gaosboy** [comment]
是不是没设置复用啊。。。如果item的frame就是屏幕尺寸，那么同一时间应该只有1个，最大3个item实例啊

**Comment by HarrisonXi** [comment]
长期无讨论，暂时关闭。需要继续讨论此问题可以继续回复。
