### ISSUE TITLE
最新更新的疑问

### ISSUE THREAD

**Issue by atom2ueki** [alibaba/LazyScrollView#15]
大致的看了一下，之前我也遇到过用Lazyscroll套在另外一个scrollview里面，外面的需要滑动，所以LazyScroll的高度需要固定，但是这样lazy loading就无效了，所以这个`outerScrollView`是用来解决这个问题的么

**Comment by gaosboy** [comment]
outerScrollView就是要把Lazy的带你方法托管给outer，这样实现lazy load
