### ISSUE TITLE
感觉delegate实现不太好

### ISSUE THREAD

**Issue by AugustRush** [alibaba/LazyScrollView#2]
重写了UIScrollView的setDelegate方法，内部用了一个变量去记录外部对delegate的设置，然后实现了所有UIScrollView的delegate方法，再对外分发delegate事件，这样实现感觉不好，写了很多没有用的代码，如果系统新版增加了一个delegate方法，岂不是要跟着更新增加这样一个方法？

**Comment by fydx** [comment]
因为LazyScrollView的复用是在滚动的时候(ScrollDidScroll内)插入代码以计算需要显示的视图，同时这样做可以让使用者”直接地“去设置UIScrollView的delegate，不需要再去在乎新的属性。目前看起来UIScrollView的delegate也是比较稳定的API。

**Comment by AugustRush** [comment]
我觉得你应该给runloop创建一个observer，观察它在kCFRunLoopBeforeWaiting状态的时候计算需要显示的视图，而不是把所有的ScrollView的delegate方法实现一遍

**Comment by gaosboy** [comment]
@AugustRush 确实是个思路，做Observer我比较担心的是性能问题~~我觉得可以试试

**Comment by AugustRush** [comment]
@gaosboy 刚刚把自己无聊时候写的demo放上去了 https://github.com/AugustRush/How-to-implement-a-ListView 可以看一下😄

**Comment by HarrisonXi** [comment]
使用对 delegate 重写和转发的方式来处理现在的逻辑，是对系统其它部分影响最小的。的确，手动手写了所有的 delegate 比较笨重，目前正在考虑用消息转发简化代码，参照我的 [pull request](https://github.com/alibaba/LazyScrollView/pull/12)。后续版本发布会把对应的改动更新上去。

**Comment by HarrisonXi** [comment]
已更新
