### ISSUE TITLE
按照文档实现代理方法，界面还是没有显示出自己添加的cell

### ISSUE THREAD

**Issue by cocalkayoun** [alibaba/LazyScrollView#5]
参考https://github.com/HistoryZhang/LazyScrollView 作者仿照写出的Demon，由于库中代码实现不同，用LazyScrollView没能实现Demo中的样式

抱歉：没仔细看目录结构，还以为没Demo。。。

**Comment by fydx** [comment]
可以具体描述一下需要实现的是什么”样式“么？
我看https://github.com/HistoryZhang/LazyScrollView 这里面的Demo实现是一个两列的样式，在我们这个仓库内的LazyScrollViewDemo中也有两列样式的实现
