### ISSUE TITLE
dequeueReusableItemWithIdentifier: 方法需要改进

### ISSUE THREAD

**Issue by zhwayne** [alibaba/LazyScrollView#7]
假如我有两个 UIView 的子类：A 和 B，我要在某个 rect 内需要填充一个 View，可能是 A 也可能是 B，取决于业务条件，类似的代码可能如下所示：

``` objective-c
UIView *view = nil;
if (some_condition) {
    view = (A *)[scrollView dequeueReusableItemWithIdentifier:reuseIdentifier_A];
    if (view == nil) {
        // create a view
        view = [A new];
        view.reuseIdentifier = reuseIdentifier_A;
    }
} else {
    view = (B *)[scrollView dequeueReusableItemWithIdentifier:reuseIdentifier_B];
    if (view == nil) {
        // create a view
        view = [B new];
        view.reuseIdentifier = reuseIdentifier_B;
    }
}

return view;
```

然后我在**第二次**调用`reloadData`方法时，数据源数据已发生变化，通过`dequeueReusableItemWithIdentifier:`方法可能会获取到错误类型的 view 实例，比如当`some_condition `条件为真时，`dequeueReusableItemWithIdentifier:`方法获取的 view 类型可能为 B。

**Comment by HarrisonXi** [comment]
1. 确认在 reloadData 之前更新了对应的 rectModelAtInde 回调结果
2. 确认 rectModelAtIndex 回调中的唯一性 muiID 进行了更新
==== 更新 ====
排查发现在没有手动设置唯一性 muiID 时如果元素顺序发生变动的确会出现这样的问题，后续版本会修复，近期发布

**Comment by HarrisonXi** [comment]
如果元素之间的顺序频繁改动，且不想自己规划设置 muiID，可以考虑在 reloadData 前使用 removeAllLayout 清空原先的复用池。

**Comment by HarrisonXi** [comment]
已经修复
