### ISSUE TITLE
- (UIView *)scrollView:(TMMuiLazyScrollView *)scrollView itemByMuiID:(NSString *)muiID 代理返回view时，

### ISSUE THREAD

**Issue by wangdxnum1** [alibaba/LazyScrollView#9]
- (UIView *)scrollView:(TMMuiLazyScrollView *)scrollView itemByMuiID:(NSString *)muiID
{
    //Find view that is reuseable first.
    LazyScrollViewCustomView *label = (LazyScrollViewCustomView *)[scrollView dequeueReusableItemWithIdentifier:@"testView"];
 // 省略代码。。。
    [scrollView addSubview:label];
    return label;
}
其它代码省略了，现在需要代理主动调用[scrollView addSubview:label];，才能把view添加到scrollview山去，是不是可以设计的跟UITableView一样，添加子视图的操作由scrollview自己来操作，代理实现者只要返回view即可，不用自己主动去把view添加到scrollview上去

**Comment by HarrisonXi** [comment]
因为目前的设计上来说，item view 不一定是直接添加到 scrollView 上的，所以没有添加自动 addSubview 功能。后续会考虑开放一个 autoAddSubview 的开关，感谢你的建议

**Comment by wangdxnum1** [comment]
谢谢回复

**Comment by HarrisonXi** [comment]
对应功能在新版里已经有了
